### ISSUE TITLE
JRE check failed with JDK11 or later

### ISSUE THREAD

**Issue by olyutorskii** [olyutorskii/Pmd2XML#3]
We can't start Pmd2XML v1.203.4 CLI with JDK11

```
Exception in thread "main" java.lang.NumberFormatException: Empty version string
	at java.base/java.lang.Package.isCompatibleWith(Package.java:281)
	at jp.sfjp.mikutoga.pmd2xml.Pmd2Xml.checkJRE(Pmd2Xml.java:211)
	at jp.sfjp.mikutoga.pmd2xml.Pmd2Xml.main(Pmd2Xml.java:413)
```

There is no problem with JDK8

**Comment by olyutorskii** [comment]
Test program
```
Package pkg = java.lang.Object.class.getPackage();
String name = pkg.getName();
String sVer = pkg.getSpecificationVersion();
String iVer = pkg.getImplementationVersion();
System.out.println(name);
System.out.println(sVer);
System.out.println(iVer);
```

JDK8 result
```
java.lang
1.8
1.8.0_382
```

JDK11 result
```
java.lang
null
null
```

So, `java.lang.Package#isCompatibleWith()` can't work with JDK11.

**Comment by olyutorskii** [comment]
[JavaSE 9 API java.lang.Package class doc](https://docs.oracle.com/javase/9/docs/api/java/lang/Package.html) has Implementation Note:

> The builtin class loaders do not explicitly define Package objects for packages in named modules. Instead those packages are automatically defined and have no specification and implementation versioning information.
